### ISSUE TITLE
application is disabled

### ISSUE THREAD

**Issue by hudyakova** [mikhailsdv/vk-remove-comments#4]
При получении токена выскакивает вот такое

**Comment by mikhailsdv** [comment]
Хммм... Кажется вк изменили client_id официального приложения VK API. Написал в поддержку. Если оперативно не решат проблему, то перейдем на приложение от Kate Mobile.

На данный момент для получения токена вы можете перейти по этой ссылке:
https://oauth.vk.com/authorize?client_id=2685278&scope=1073737727&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token&revoke=1

**Comment by hudyakova** [comment]
спасибо, всё получилось))
