### ISSUE TITLE
New Vk token problem

### ISSUE THREAD

**Issue by wizardneon** [mikhailsdv/vk-remove-comments#5]
changed, now some akks have a new token, which contains ml at the beginning, contains characters uncharacteristic of the previous small token (such as dots, dashes and underscores) and reaches almost 200 characters (in any case, I have not seen longer so far) my token with vk1.a. says not valid

**Comment by mikhailsdv** [comment]
I'm currently working on a fix. It may take 2-3 days cause there are some more issues except token that I want to fix as well. I'll warn you and close this issue as soon as I commit a fix.

**Comment by mikhailsdv** [comment]
Oh, I did it faster than I expected. Fix is already in the repo. Please, download project files once again and make another attempt to remove your comments. Open new issue if something goes wrong. Remember that with this update you have to paste full url to console, not just access_token part.

**Comment by wizardneon** [comment]
Oh, thanks a lot. this is very important right now. talk about peace and not go to jail for complaining about comments
